baseurl = "https://golangcode.com/"
languageCode = "en-GB"
ignoreFiles = [ "\\.scss" ]
title = "GolangCode"
theme="site-theme"

[outputs]
	home = ["HTML", "RSS", "JSON"]

[params]
	name = "Golang Code"
	description = "A Library of Go Snippets"
	bio = "A Library of Go Snippets"
	author = "Edd Turtle"
	twitter = "golangcode"
	enableRSS = true
	enableDisqus = true
	disqusShortname = "golangcode"

[social]
	rss-squared = "/index.xml"
	twitter-squared = "https://twitter.com/golangcode"
	github-squared = "https://github.com/eddturtle/golangcode-site"

[deployment]
	order = [".jpg$", ".gif$"]

	[[deployment.targets]]
		name = "live"
		URL = "s3://golangcode.com?region=eu-west-1"
		cloudFrontDistributionID = "E11H7N5DSISWX8"

	[[deployment.matchers]]
		#  Cache static assets for 20 years.
		pattern = "^.+\\.(js|css|svg|ttf)$"
		cacheControl = "max-age=630720000, no-transform, public"
		gzip = true

	[[deployment.matchers]]
		pattern = "^.+\\.(png|jpg|gif|webm|mp4)$"
		cacheControl = "max-age=630720000, no-transform, public"
		gzip = false

	[[deployment.matchers]]
		pattern = "^.+\\.(html|xml|json)$"
		gzip = true